spring:
  datasource:
    druid:
        driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
        url: jdbc:mysql://localhost:3306/guns              # 数据库名称
        username: root
        password: root
        initial-size: 5
        max-active: 20
        test-on-borrow: true
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200                                  # 等待连接获取的最大超时时间





